#BNF+IAT 1.0 UTF-8;
!grammar talker;

!slot <want>;
!slot <content>;

!start <begintalk>;
<begintalk>:[<want>]<content>;


<want>:我想要找!id(1)|我想找!id(1)|我找!id(1)|找一下!id(1);


<content>:汪鹏!id(1)|常先明!id(2)|常总!id(3)|方洋!id(4)|方总!id(5)|会议!id(6)|会议室!id(7)|你好!id(1001)|你叫什么名字!id(1002)|你多大了!id(1003)|你几岁了!id(1004)|你来自哪里!id(1005)|介绍一下你自己!id(1006)|你自我介绍一下!id(1007)|介绍你自己!id(1008)|再见!id(1009)|很高兴见到你!id(1010)|你会做什么!id(1011)|你会什么!id(1012)|你是谁!id(1013);
